# Site
url: ""
baseurl: ""
permalink: /:title/

# Plugins STANDARD saja (tanpa custom)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives (untuk categories saja)
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/?q=:name'
    
# Pagination 
paginate: 50
paginate_path: 'page:num'
    
# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

